health_care_booking/src/main/java/health/care/booking/controllers/AuthController.java, health_care_booking/src/main/java/health/care/booking/dto/RegisterRequest.java, health_care_booking/src/main/java/health/care/booking/dto/RegisterResponse.java, health_care_booking/src/main/java/health/care/booking/models/User.java, health_care_booking/src/main/java/health/care/booking/services/UserService.java, health_care_booking/src/test/java/health/care/booking/SignUpTest.java, medical-app-client/package-lock.json, medical-app-client/src/App.jsx, medical-app-client/src/components/Home.jsx, medical-app-client/src/components/Login.jsx, medical-app-client/src/components/Signup/Signup.css, medical-app-client/src/components/Signup/Signup.jsx
Registrera användare
Backend:
* lagt till: mail, förnamn och efternamn
* mock register-test
Frontend:
* register page på "/signup", med knapp för att återgå till /home om man redan har ett konto
- Prova skapa konto och se så det sparas i DB
- Ange fel i inputs och se så felhantering är korrekt
- Kontrollera och kör tester i backend
- Kodgranska, kontrollera
- Recenserare: 1 
* lämna kommentar på funktion om du önskar justering av något
* Design/utseende är irrelevant i denna skoluppgift
--
Closes #10
=> 10 register page

medical-app-client/package-lock.json, medical-app-client/src/components/AdminDashboard.jsx, medical-app-client/src/components/Login.jsx, medical-app-client/src/components/UserDashboard.jsx, medical-app-client/src/components/footer/Footer.css, medical-app-client/src/components/footer/Footer.jsx
What i did :
i created a footer for patient and doctor. 
What to test :
test if the footer works, 
first import Footer from "./footer/footer";
and then use this 
/// <Footer userType="doctor" />  for the doctor
/// <Footer userType="patient" /> for the patient
first one for the doctor page 
and the another one for the patient
=>  Fotter for the doctor and patient works

.github/workflows/actions.yaml, src/main/java/health/care/booking/controllers/AuthController.java
- Lagt till ett workflow för github actions backend. Det som kommer ske när vi mergar en pull request till dev eller main grenen är enkelt förklarat bygger ihop och testar. Mer om flödet kan utläsas i actions.yaml filen.
- Byt till till denna branchen och gör någon ändring någonstans, en test kommentar eller nått. Sedan gör en commit och push, byt över till repot och gå in på branchen sedan Actions. Där inne borde det se ut ungefär såhär:
- Recenserare: 1
- Synpunkter?
=> 20 ci pipeline backend

.github/workflows/actions.yaml, src/main/java/health/care/booking/services/PasswordResetService.java
Lagt till mail stuff i application.properties till github actions.
Gör någon justering å se om actions rullar igenom korrekt.
=> Ci-Pajplajn

src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/controllers/AvailabilityController.java, src/main/java/health/care/booking/models/Appointment.java, src/main/java/health/care/booking/services/AppointmentService.java, src/test/java/health/care/booking/AppointmentServiceTest.java
har ändrat från dbref till String på allt som har med id att göra (appointment)
testa genom att:
boka en appointment i browsern - kolla databas så den skapades
boka i tex postman - kolla databas
http://localhost:8080/appointment/new
{
"username": "stringid",
"caregiverId": "676ec624d29cdb168b12346f",
"availabilityId": "677d1be1562d6966269a6519",
"availabilityDate": "2025-01-15T09:00:00.000+00:00"
}
Closes #43
=> dbref to string

documentation/documentation availability.txt, src/main/java/health/care/booking/controllers/AvailabilityController.java, src/main/java/health/care/booking/models/Availability.java, src/main/java/health/care/booking/respository/AvailabilityRepository.java, src/main/java/health/care/booking/services/AvailabilityService.java, src/test/java/health/care/booking/AppointmentServiceTest.java, src/test/java/health/care/booking/AvailabilityTests.java
Whats done 
Refactored all the availability references to caregiverId as user to String.
Whats to be tested
Test availability endpoints
Others
Reviewer: 1
be thorough with the endpoints
Do #46 first
=> Refactored caregiverId Availability

src/main/java/health/care/booking/controllers/AuthController.java, src/main/java/health/care/booking/respository/UserRepository.java
-- En ny boolean metod koll i userRepository för snabbare existenskontroll
-- En koll i endpoint  /register, kollat att mejl adressen inte redan finns tilldelad till en användare.
- Testa att registrera en ny användare med ett username och en mejladress som ni redan vet används till en annan användare.
- fel meddelande får fixas i frontend när tid finns ?
Closes #51
=> UserMail & Username @unique

src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/dto/AvailabilityUserIdRequest.java, src/main/java/health/care/booking/dto/AvailabilityUserIdResponse.java, src/main/java/health/care/booking/services/UserService.java
What's done:
- Added new Endpoint api /find/caregivers-by-availability
This gets a AvailabilityUserIdResponse from the new api with filtered data of a caregiver.
What to test:
- Throw in a bunch of caregiver Id's
- Should return objects with 
caregiverId
firstname
lastname
username
Others: 
Reviewers: 1
=> Fixed so that calendar and schedule works with frontend

documentation/documentation appointment.txt, src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/respository/AppointmentRepository.java, src/main/java/health/care/booking/services/AppointmentService.java, src/test/java/health/care/booking/AppointmentServiceTest.java, src/test/java/health/care/booking/UserControllerTest.java
whats done?
två nya metoder i appointment:
how to test:
KÖRS IHOP MED BRANCH 37 I FRONTEND OM INTE DEN ÄR MERGED TILL DEV
se documentation eller nedan
1 = user
2 = admin
http://localhost:8080/appointment/history/1/viktor            (GET)
http://localhost:8080/appointment/history/2/viktor           (GET)
en ny i usercontroller:
how to test:
http://localhost:8080/user/full-name/676e9d2a2937a24dbe28c5b1
Other:
hittat några fel? let me know in the comments
Closes #18
=> 18 appointment history

src/main/java/health/care/booking/services/PasswordResetService.java, src/test/java/health/care/booking/BookingApplicationTests.java, src/test/java/health/care/booking/PasswordResetServiceTest.java
Setup:
branch: 54-enhetstester-backend-email
- Skapat PasswordResetServiceTest klass i Test mappen
Tester som har skapats i testklassen
- testSendPasswordResetLink_Success
- testSendPasswordResetLink_Failure
- testValidateToken_Success
- testValidateToken_Failure
- testUpdatePassword_Success
- testUpdatePassword_Failure
Lagt till kommentarer för nästan all så att det ska vara smidigt att review om man känner sig osäker.
- Tog bort JavaMailSender i PasswordResetService filen 
- tog bort @Mock JavaMailSender mailsender; i BookingApplicationTests då jag nu använder mig av den i mitt test.
Kör samtliga tester i PasswordResetServiceTest och kolla så att alla går igenom.
Kör en Code Review på samtliga tester så att det inte ser galet ut.
Det är tyvärr inte så mycket mer att kolla då denna PR …
=> 54 enhetstester backend PasswordResetTest

src/main/java/health/care/booking/controllers/AvailabilityController.java, src/main/java/health/care/booking/services/AvailabilityService.java, src/test/java/health/care/booking/AvailabilityTests.java
Whats done
Changed name on "Change availability" to "remove availability"
Added /add-availability (uses same RequestDTO as removeAvailability)
Added tests
What to test
Try and adding availability times to an existing availability 
If there are Dates that are the same it should return "No dates have been added, most likely duplicates."
if there aren't duplicates it should return "Selected times were added: " and the dates.
Others: Reviewer 1
=> 78 update availability add timeslots

src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/controllers/AvailabilityController.java, src/main/java/health/care/booking/controllers/FeedbackController.java, src/main/java/health/care/booking/services/FeedbackService.java, src/test/java/health/care/booking/FeedbackTests.java
What i did:
All that i could find that uses admin where it should be doctor instead.
Added the right permissions for all backend api calls on for the right role/roles.
What to test
Check so that you can use the program in an expected manner with the api calls, and the frontend.
Didn't change too much but this might be difficult because it was a lot of different files (5). 
Other: 
Reviewers: 2 to be sure
closes #74
=> Fixed Admin -> Doctor

src/main/java/health/care/booking/controllers/FeedbackController.java, src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/dto/FeedbackAverageGradeAllResponse.java, src/main/java/health/care/booking/services/FeedbackService.java, src/test/java/health/care/booking/FeedbackTests.java
Whats been done: 
Added a controller for feedbackAverageResponseMethod
/feedback/find/average-grade/{username}
/feedback/find/average-feedback/all
Only pedro has Feedbacks tied to the user
How to test
/find/average-grade/pedro
Should return 3.0
/feedback/find/average-feedback/all
pedro should have 3.0, the rest has no feedback
Other:
Reviewer 1
Closes #67
=> Feedback grade

documentation/feedback.txt, src/main/java/health/care/booking/config/SecurityConfig.java, src/main/java/health/care/booking/controllers/FeedbackController.java, src/main/java/health/care/booking/respository/FeedbackRepository.java, src/main/java/health/care/booking/services/FeedbackService.java, src/test/java/health/care/booking/FeedbackTests.java
- En extra tillagd metod för att hämta feedback som en patient har givit.
- Uppdaterat dokumentation
- Samkör du denna med frontend PR "**32 feedback frontend**" så testar du även denna branch.
- Mergas när frontend PR är okej.
=> 73 bug feedback already given

src/main/java/health/care/booking/config/SecurityConfig.java, src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/controllers/AvailabilityController.java
Whats done:
Added requestMatchers in SecurityConfig to make permissions work
What to test:
Check so that the correct user role works with the correct @PreAuthorize per call
Others: Reviewer 1
=> Fix permissions

src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/respository/AvailabilityRepository.java, src/main/java/health/care/booking/services/AppointmentService.java
Whats added: 
Added so if you cancel an appointment it adds the availability back to the correct availability object and for the right caregiver.
What to test:
Use a user to book an appointment (Frontend or backend), this does not work with appointments that are earlier than now, backend it works with the same day, but not on frontend.
Then try cancelling it, either use the frontend Appointment Details page or use the Backend http://localhost:8080/appointment/change-status/:status/:id
Other: Reviewer 1
closes #75
=> Cancelled appointments

src/main/java/health/care/booking/controllers/AuthController.java, src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/dto/RegisterRequest.java, src/main/java/health/care/booking/dto/UpdateURLRequest.java, src/main/java/health/care/booking/models/User.java, src/main/java/health/care/booking/services/UserService.java
What's done:
Added 
update-user-picture/{username}
and
/find/userURL/{username} 
if the url isnt part of the bucket then it won't work in the frontend, because it's a string and it's case-sensitive.
What to test:
http://localhost:8080/user/update-user-picture/:username
body: {
url: String
}
http://localhost:8080/user/find/userURL/:username
make sure they match.
Frontend: https://github.com/johnsson84/HealthCareAB_Frontend/pull/43
=> Added logic to handle set urls

documentation/documentation mail.txt, src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/controllers/MailController.java, src/main/java/health/care/booking/dto/AppointmentRequest.java, src/main/java/health/care/booking/dto/SendMail.java, src/main/java/health/care/booking/models/Appointment.java, src/main/java/health/care/booking/services/AppointmentService.java, src/main/java/health/care/booking/services/MailService.java, src/test/java/health/care/booking/AppointmentServiceTest.java
- Ändrat **summary** i appointment till **reason**.
- Justerat allt annat i backend till att använda **reason**.
- Testa att skapa en appointment, byt ut **summary** mot **reason**.
- Recenserare: 1
- Förhoppningsvis har jag inte missat något.
- Denna branchen samkörs med frontend PR "**55 change name of summary**"
- Mergas när frontend PR också är okej
=> changed summary for reason

src/main/java/health/care/booking/controllers/AvailabilityController.java, src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/dto/AvailabilityUserIdResponse.java, src/main/java/health/care/booking/services/UserService.java
What's done
Changed the "/find/caregivers-by-availability" call to return specialities
how to test
Send availabilityId in an array
get back response object with all relevant info
others this is the backend for bookDoctorChanges
=> Change book doctor backend

src/main/java/health/care/booking/controllers/AuthController.java, src/main/java/health/care/booking/controllers/FacilityController.java, src/main/java/health/care/booking/dto/RegisterDoctorRequest.java, src/main/java/health/care/booking/models/User.java, src/main/java/health/care/booking/services/FacilityService.java
- register coworker AND add coworker to facility
http://localhost:8080/auth/register/caregiver/:facilityId
{
"username": "username",
"password": "password",
"mail": "mail",
"firstName": "firstName",
"lastName": "lastName",
"specialities": "special"
}
Path variable: facilityId
- add coworker to facility
ingår i move coworker
- remove coworker from facility
ingår i move coworker
- move coworker from facility
http://localhost:8080/facility/move/coworker/:oldFacilityId/:newFacilityId/:userId
path variables:
- oldFacilityId : facilityId (den som coworker är på nu)
- newFacilityId : facilityId (den som coworker ska till)
- userId : coworkers userId
- Recenserare: 1 
- kontrollera med postman
Closes #64 #93
=> register caregiver and add/remove/move coworker to facility

src/main/java/health/care/booking/controllers/AppointmentController.java, src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/services/AppointmentService.java
fixed the appointmentController CreateNewAppointment to not have all logic in the controller
=> Refactor AppointmentController

documentation/feedback.txt, src/main/java/health/care/booking/config/SecurityConfig.java, src/main/java/health/care/booking/controllers/FeedbackController.java, src/main/java/health/care/booking/dto/FeedbackHighRating.java, src/main/java/health/care/booking/respository/FeedbackRepository.java, src/main/java/health/care/booking/services/FeedbackService.java, src/test/java/health/care/booking/FeedbackTests.java
- Ny feedback metod för att hämta all feedbacks och sortera ut dem med 4 eller 5 i rating samt hämta doktorers fullständiga namn som sen sparas i en ny feedback dto som skickas till frontend.
- Dokumentation
- Ett nytt test
- Inte så mycket att testa då detta är en hjälp metod till frontend delen
GET http://localhost:8080/feedback/find/doctors-highrating
- Testet
- Recenserare: 1
=> Doctor show off

src/main/java/health/care/booking/BookingApplication.java, src/main/java/health/care/booking/controllers/FacilityController.java, src/main/java/health/care/booking/controllers/MailController.java, src/main/java/health/care/booking/respository/AppointmentRepository.java, src/main/java/health/care/booking/services/AppointmentService.java, src/main/java/health/care/booking/services/MailService.java, src/main/java/health/care/booking/services/ScheduleService.java
What's done: 
Made it so that the system automagically sends reminders 1 time per day to people who have appointments that are scheduled and on the same date.
How to test:
Make an appointment with a user you have access to their email.
In the new ScheduleService set the time to a minute away from your time. ( i'ts reversed so it's sec, min, H)
Wait until the next minute ticks over and see if you got a reminder in your inbox
Reviewer: 1
=> Notification24 hrs

src/main/java/health/care/booking/controllers/UserController.java, src/main/java/health/care/booking/dto/UserUpdateRequest.java, src/main/java/health/care/booking/models/User.java, src/main/java/health/care/booking/services/UserService.java
Added so you can update your user with more info and also change email.
What to test: 
This api call, i used the FacilityAddress object to add address for the user.
http://localhost:8080/user/update/user-information/:userId
{
"mail": "test@mail.jesus.se",
"birthDate": "19950626",
"phoneNmr": "+46709544189",
"address": {
"street": "gata",
"city": "staden",
"postcode": 12345,
"region": "en av dem",
"country": "sweden"
}
}
Reviewer 1
=> Add info to users

src/main/java/health/care/booking/services/FacilityService.java
WHAT IS DONE:
fixed an error where users facilityId didn't update
fixed an error in removeCoworkerFromFacility
- forEach instead of if
HOW TO TEST:
run with branch 77-move-coworker i frontend
login as admin
navigate to Edit coworkers location
change location
check db before and after
OTHER:
function etc
=> save new facilityId to user

documentation/conditions.txt, src/main/java/health/care/booking/controllers/ConditionsController.java, src/main/java/health/care/booking/dto/CreateCondition.java, src/main/java/health/care/booking/models/Conditions.java, src/main/java/health/care/booking/models/ConditionsCategory.java, src/main/java/health/care/booking/respository/ConditionsRepository.java, src/main/java/health/care/booking/services/ConditionsService.java, src/test/java/health/care/booking/ConditionsTests.java
- Ny modell för conditions
- Nya metoder
- 2 tester
- Dokumentation
- Postman
List all conditions
GET http://localhost:8080/conditions/all
Add a condition
POST http://localhost:8080/conditions/add
{
"name": "Fever",
"description": "Solution: Headache pills",
"category": "disease"
}
Delete a condition
DELETE http://localhost:8080/conditions/delete/{id}
- Kör tester
- Recenserare: 1
=> 109 search problems and diseases backend

src/main/java/health/care/booking/models/ConditionsCategory.java, src/main/java/health/care/booking/services/ConditionsService.java
- Lagt till enums till conditions
- INJURIES
- ALLERGIES
- Testa att skapa en ny condition
=> added more enums for conditions

README.md, src/main/java/health/care/booking/controllers/MailController.java, src/main/java/health/care/booking/controllers/UserController.java
- Lagt till API calls till readme filen
- Kolla så allt ser korrekt ut
- Är det något som saknas till filen?
=> updated readme with all api calls

src/test/java/health/care/booking/UserControllerTest.java
That i did :
created test fot findUserByid
what to do :
test testFindFullNameByUserId_Exception
=> added a test
